name: Build and Deploy rvc-web

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build with Vite
        run: npm run build

      - name: Log in to Docker Hub
        run: docker login -u tmllab -p Tml123456

      - name: Build Docker image
        run: docker build -t tmllab/rvc-web .

      - name: Push Docker image
        run: docker push tmllab/rvc-web

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 1.94.28.8
          username: root
          password: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            docker stop RvcGatewayContainer || true
            docker rm RvcGatewayContainer || true
            docker rmi $(docker images tmllab/rvc-web -q) || true 
            sleep 3
            docker pull tmllab/rvc-web
            docker run -d --name RvcGatewayContainer -p 8090:8090 tmllab/rvc-web
