name: Build and Deploy RvcWeb

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build with Vite
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t your-docker-username/your-image-name .

      - name: Push Docker image
        run: docker push your-docker-username/your-image-name

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: your-server-hostname
          username: your-server-username
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            docker stop your-container-name || true
            docker rm your-container-name || true
            docker pull your-docker-username/your-image-name
            docker run -d --name your-container-name -p 80:80 your-docker-username/your-image-name
