name: Build and Deploy RvcWeb

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build with Vite
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t TmlLab/RvcWeb .

      - name: Push Docker image
        run: docker push TmlLab/RvcWeb

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 62.234.54.176
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            docker stop RvcContainer || true
            docker rm RvcContainer || true
            docker pull TmlLab/RvcWeb
            docker run -d --name RvcContainer -p 8090:80 TmlLab/RvcWeb
